export enum AppRoutes {
    HOME = '/',
    SIGNIN = '/signin',
    SIGNUP = '/signup',
    CART = '/cart',
    PRODUCT = '/product',
    PROFILE = '/profile',
    SHIPPING = '/shipping',
    PAYMENT = '/payment',
    CHECKOUT = '/checkout',
    PLACE_ORDER = '/place_order',
    ORDER_SUCCESS = '/order_success',
    ORDER_DETAILS = '/order_details',

    ADMIN = '/admin',
    ADMIN_DASHBOARD = '/dashboard',
    ADMIN_USER_LIST = '/users',
    ADMIN_ORDER_LIST = '/orders',
    ADMIN_PRODUCT_LIST = '/products',
}
